### ISSUE TITLE
Zjednodušení buildu

### ISSUE THREAD

**Issue by lttr** [krouma/Ctyriadvacitka#2]
Všechny kroky pro rozjetí projektu jsou sice popsané ale přesto nelze (na Ubuntu 16) spustit automatickou přípravu prostředí (bin/setup.sh).

- S Vagrantem 1.8.x nefunguje instalace pluginu, s 1.9.x již ano
- Je potřeba balíček `ruby-dev`?
- Na Ubuntu 16 je již defaultně php7, nikoli `php5-cli`
- Do _npm start_ bych nedával _npm install_, nechme to jako samostatný příkaz
- _sudo_ by mělo být u jednotlivých příkazů ve skriptu _setup.sh_, nepatří totiž všem - např. vagrant, cp, npm může být bez _sudo_
- Provisioning vagrantu trvá hodně dlouho, možná by existovalo řešení, které by se bylo rychlejší a s jednodušší konfigurací (předpřipravený vagrant box, možná docker)

**Comment by krouma** [comment]
* V době, kdy byla nejnovější verze Vagrantu 1.9.3 jsem používal 1.8.něco a fungovalo to. Zkus sem dát chybovou hlášku
* ruby-dev: Napsal jsem si tam komentář, že je potřeba k instalaci pluginu, takže ano, ale můžeš to zkusit bez něj.
* php7: Zjistil jsem, že v Ubuntu 16 už je `composer` v repozitáři, takže si php natáhne sám
* npm install: OK, změněno
* sudo u příkazů: Dobře, změním to
* provisioning: Pracuju na tom, že si vytvořím další repozitář s builděním boxu, ten pak nahraju na Atlas a v tomto Vagrantfile použiju basebox `krouma/lamp`. S dockerem jsem nikdy nepracoval, ale někdy bych to chtěl zkusit, tak spíš později

**Comment by krouma** [comment]
* sudo u příkazů: 1c064efa741d84ad6436349f12872e095890ce0e
* provisioning: cf44c243291409632e27109d5be807cb06f55dd7

**Comment by krouma** [comment]
Tím, že už používáme box, který obshuje `guest addition`, není potřeba instalovat `ruby-dev` a zároveň by neměl být žádný problém s verzemi Vagrantu. 
Taky by bylo lepší otevírat pro každý problém samostatné issue.
